### ISSUE TITLE
add support Alex's Mobs

### ISSUE THREAD

**Issue by GitJhopa** [MCTeamPotato/GoalOptimizer#1]
add support Alex's Mobs

**Comment by Kasualix** [comment]
Which mc version do you prefer?

**Comment by GitJhopa** [comment]
1.19.2 Forge

**Comment by GitJhopa** [comment]
There, animals heavily load the game, such as an elephant and a leopard

**Comment by GitJhopa** [comment]
https://spark.lucko.me/RjTTMAsaHP

**Comment by GitJhopa** [comment]
![image](https://github.com/MCTeamPotato/GoalOptimizer/assets/86250668/f243f8b1-c009-4fa9-808a-c7f5d2a63a45)
![image](https://github.com/MCTeamPotato/GoalOptimizer/assets/86250668/7b6948d9-bdc6-4fba-9996-161606482d2f)

**Comment by Kasualix** [comment]
Ok, I'll add support for it after my two-day vacation trip

**Comment by Kasualix** [comment]
No, it's not about the goals, it's about pathfinder that causes lag. The impact of the goals on performance is very minimal. removing them won't do any notable increase on performance.
