### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by ForestLive6** [MCTeamPotato/GoalOptimizer#2]
Hi, adding a mod to the server, the server crashes. With what is connected I do not understand. 
[crash-2023-06-29_17.28.52-server.txt](https://github.com/MCTeamPotato/Redirectionor/files/11906828/crash-2023-06-29_17.28.52-server.txt)
[latest.log](https://github.com/MCTeamPotato/Redirectionor/files/11906829/latest.log)

**Comment by ForestLive6** [comment]
As I understand the mod Redirectionor does not crash the server.
That's what Goal Optimizer does.
But I noticed a strange thing, if you add to the server mod RoadRunner, a bunch of mods from Goal Optimizer + RoadRunner + Redirectionor works. If you install Goal Optimizer + Redirectionor, the server crashes.

**Comment by Kasualix** [comment]
because GoalOptimization will disable its optimization when RoadRunner is installed

**Comment by Kasualix** [comment]
And RoadRunner does not optimize this removeGoal method and won't crash the Vampirism

**Comment by Kasualix** [comment]
Can you try this build? https://filebin.net/dtpl11blrq8l1p7d

**Comment by ForestLive6** [comment]
> Can you try this build? https://filebin.net/dtpl11blrq8l1p7d

It works, the server did not crash.

**Comment by Kasualix** [comment]
The removeGoal method optimization is disabled when Vampirism is installed as a workaround now, but can you report this to Vampirism to ask them to change their impl? They modify entities' target selector onEntityJoinWorld, which may cause a performance issue similar to AI Improvements when many entities join world at one time (If the server have alexsmobs or mods that add many animals this issue will become even more severe). I think they can directly use mixin to tweak the entities goals registry.
You can tell me if you don't want to, I can go create a issue for them myself tomorrow, but for now I'm going to bed.
